name: Publish CI

on:
  push:
    branches: [ "main" ]

env:
  USERNAME: ${{ secrets.DIGITRON_GPR_USERNAME }}
  TOKEN: ${{ secrets.DIGITRON_GPR_TOKEN }}

jobs:
  publish:
    runs-on: macos-15
    steps:
      - name: Set tag version to ENV
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          #can write cache on [main] branch only, should work by default, but don't
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          #ndk lts version 27.3.13750724
          packages: ndk;27.2.12479018 # build-tools;36.0.0 platforms;android-36 #cmake;3.6.4111459
          log-accepted-android-sdk-licenses: false
      - name: Build and Publish PatchCore with Gradle
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_IN_MEMORY_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: ./gradlew PatchCore:publishAllPublicationsToMavenCentralRepository -PgitTag=${TAG_VERSION}
      - name: Build and Publish PatchCoreMultiplatform with Gradle
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_IN_MEMORY_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: ./gradlew PatchCoreMultiplatform:publishAllPublicationsToMavenCentralRepository -PgitTag=${TAG_VERSION}

